{{- if and .Values.backup.enabled (not .Values.backup.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-sentinel.instanceName" . }}-backup-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
    app: {{ include "redis-sentinel.redisName" . }}
type: Opaque
stringData:
  access-key: {{ .Values.backup.accessKey | quote }}
  secret-key: {{ .Values.backup.secretKey | quote }}
{{- end }}
