{{- if and .Values.common.auth.enabled (not .Values.common.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-sentinel.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
    app: {{ include "redis-sentinel.redisName" . }}
type: Opaque
stringData:
  redis-password: {{ .Values.common.auth.password | quote }}
{{- end }}
